Posmtracker/config/routes.rb
Posmtracker::Application.routes.draw do
  

 

        root :to => "employees#index"

      get "/posm_tracker" => "employees#index"

  
  match ':controller(/:action(/:id))(.:format)'
  
  resources :company_details

  resources :branch_details

  resources :employee_roles

  resources :employees

  resources :uploaded_images
    
  resources :images_multi_brands
  
  resources :employee_authentications
  
  resources :brand_details
  
   resources :customer_details

  resources :posm_types
  
  resources :kd_details

  resources :principal_details

end

Posmtracker/app/models/principal_detail.rb
class PrincipalDetail < ActiveRecord::Base
  # attr_accessible :title, :body
  set_table_name "PRINCIPAL_MASTER"
 
 
   alias_attribute :id , :SEQ_NUM

  attr_accessible :principal_name ,:principal_code , :id

  def self.get_details()
     details = Array.new
          branch_name = PrincipalDetail.find(:all,:order => "principal_name ASC")
          branch_name.each do |val|
              hash = Hash.new
              hash["name"] = val.principal_name
              hash["id"] = val.id
              
              details << hash
            
          end 
      return details
  end
  
  
  def self.get_principal_id_using_brand(brand_id)
      
      brand_details = BrandDetail.find(:first ,:conditions => {:SEQ_NUM => brand_id})
      if (brand_details)
          principal_code = brand_details.principal
          principal_name = PrincipalDetail.find(:first, :conditions => {:principal_code => principal_code})
          return principal_name.id

      end          
      return ""
  end
  
  
   def self.get_brand_using_principal(principal_id)
           details = Array.new

       principal_details = PrincipalDetail.find(:first, :conditions => {:SEQ_NUM => principal_id})

      if (principal_details)
          principal_code = principal_details.principal_code
           brand_details = BrandDetail.find(:all ,:conditions => {:principal => principal_code})
           
             brand_details.each do |val|
              hash = Hash.new
              hash["name"] = val.name
              hash["principal_id"] = val.principal
              hash["id"] = val.id
              
              details << hash
            
          end 
          return details

      end          
      return []
  end
  
end

Posmtracker/app/controllers/principal_details_controller.rb
class PrincipalDetailsController < ApplicationController
  
  
  
end

Posmtracker/app/helpers/principal_details_helper.rb
module PrincipalDetailsHelper
end

Posmtracker/app/views/principal_details/_form.html.erb
<%= form_for(@principal_detail) do |f| %>
  <% if @principal_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@principal_detail.errors.count, "error") %> prohibited this principal_detail from being saved:</h2>

      <ul>
      <% @principal_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Posmtracker/app/views/principal_details/edit.html.erb
<h1>Editing principal_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @principal_detail %> |
<%= link_to 'Back', principal_details_path %>

Posmtracker/app/views/principal_details/index.html.erb
<h1>Listing principal_details</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @principal_details.each do |principal_detail| %>
  <tr>
    <td><%= link_to 'Show', principal_detail %></td>
    <td><%= link_to 'Edit', edit_principal_detail_path(principal_detail) %></td>
    <td><%= link_to 'Destroy', principal_detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Principal detail', new_principal_detail_path %>

Posmtracker/app/views/principal_details/new.html.erb
<h1>New principal_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', principal_details_path %>

Posmtracker/app/views/principal_details/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_principal_detail_path(@principal_detail) %> |
<%= link_to 'Back', principal_details_path %>