salestracker/config/routes.rb
Locationtracker::Application.routes.draw do

  

    root :to => "employees#index"

    get "/location_tracker" => "employees#index"

  match ':controller(/:action(/:id))(.:format)'
  
    resources :employees
    
    resources :actual_routes

    resources :planned_routes

    resources :branch_details

    resources :company_details

    resources :employee_roles

    resources :temp_emp_trees
    
    resources :customer_details
      
    resources :kd_details

end

salestracker/app/models/customer_detail.rb
class CustomerDetail < ActiveRecord::Base
  # attr_accessible :title, :body
 set_table_name "CUSTOMER_MASTER"
  
    alias_attribute :address_line1, :Address_line1
  alias_attribute :address_line2, :Address_line2
  alias_attribute :address_line3, :Address_line3
  alias_attribute :lat, :GPS_latitude
  alias_attribute :lng, :GPS_longitude
  
    attr_accessible :address_line1, :address_line2 ,:address_line3 , :lat , :lng, :customer_name , :company_code


 # GET IMAGE ADDRESS
  def self.get_addtrss(customer_code)
    
      sql=""
      s =""
      arr = Array.new
      address = ""
      hash = Hash.new
        # sql << "select customer_name,Address_line1,Address_line2,Address_line3,city from CUSTOMER_MASTER where customer_code = "+customer_code
            # sql << "select * from uploaded_images where employee_id= 28 order by employee_id desc limit 9,9"
            s = CustomerDetail.find(:first,:conditions =>{:customer_code => customer_code}) 
           
           arr = [s.address_line1,s.address_line2,s.address_line3,s.city]
            arr.each do |val|
              if address.present?
                 address = "#{address}#{','}"
              end
              if val.present?
                 address = "#{address}#{val}"
              end
              
            end
            hash['address'] = address
            # hash['phone_number'] = s.phone_number
            hash['name'] = s.customer_name
            hash['lat'] = s.lat
            hash['lng'] = s.lng
            
       return hash   
  end

end

salestracker/app/controllers/customer_details_controller.rb
class CustomerDetailsController < ApplicationController
  # GET /customer_details
  # GET /customer_details.json
  def index
    @customer_details = CustomerDetail.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @customer_details }
    end
  end

  # GET /customer_details/1
  # GET /customer_details/1.json
  def show
    @customer_detail = CustomerDetail.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @customer_detail }
    end
  end

  # GET /customer_details/new
  # GET /customer_details/new.json
  def new
    @customer_detail = CustomerDetail.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @customer_detail }
    end
  end

  # GET /customer_details/1/edit
  def edit
    @customer_detail = CustomerDetail.find(params[:id])
  end

  # POST /customer_details
  # POST /customer_details.json
  def create
    @customer_detail = CustomerDetail.new(params[:customer_detail])

    respond_to do |format|
      if @customer_detail.save
        format.html { redirect_to @customer_detail, notice: 'Customer detail was successfully created.' }
        format.json { render json: @customer_detail, status: :created, location: @customer_detail }
      else
        format.html { render action: "new" }
        format.json { render json: @customer_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /customer_details/1
  # PUT /customer_details/1.json
  def update
    @customer_detail = CustomerDetail.find(params[:id])

    respond_to do |format|
      if @customer_detail.update_attributes(params[:customer_detail])
        format.html { redirect_to @customer_detail, notice: 'Customer detail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @customer_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customer_details/1
  # DELETE /customer_details/1.json
  def destroy
    @customer_detail = CustomerDetail.find(params[:id])
    @customer_detail.destroy

    respond_to do |format|
      format.html { redirect_to customer_details_url }
      format.json { head :no_content }
    end
  end
end

salestracker/app/helpers/customer_details_helper.rb
module CustomerDetailsHelper
end

salestracker/app/views/customer_details/_form.html.erb
<%= form_for(@customer_detail) do |f| %>
  <% if @customer_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer_detail.errors.count, "error") %> prohibited this customer_detail from being saved:</h2>

      <ul>
      <% @customer_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

salestracker/app/views/customer_details/edit.html.erb
<h1>Editing customer_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer_detail %> |
<%= link_to 'Back', customer_details_path %>

salestracker/app/views/customer_details/index.html.erb
<h1>Listing customer_details</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @customer_details.each do |customer_detail| %>
  <tr>
    <td><%= link_to 'Show', customer_detail %></td>
    <td><%= link_to 'Edit', edit_customer_detail_path(customer_detail) %></td>
    <td><%= link_to 'Destroy', customer_detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Customer detail', new_customer_detail_path %>

salestracker/app/views/customer_details/new.html.erb
<h1>New customer_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', customer_details_path %>

salestracker/app/views/customer_details/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_customer_detail_path(@customer_detail) %> |
<%= link_to 'Back', customer_details_path %>