Posmtracker/config/routes.rb
Posmtracker::Application.routes.draw do
  

 

        root :to => "employees#index"

      get "/posm_tracker" => "employees#index"

  
  match ':controller(/:action(/:id))(.:format)'
  
  resources :company_details

  resources :branch_details

  resources :employee_roles

  resources :employees

  resources :uploaded_images
    
  resources :images_multi_brands
  
  resources :employee_authentications
  
  resources :brand_details
  
   resources :customer_details

  resources :posm_types
  
  resources :kd_details

  resources :principal_details

end

Posmtracker/app/controllers/posm_types_controller.rb
class PosmTypesController < ApplicationController
 
 
 def get_brand_details
#     
    # brand_id = params['brand_id']
#     
    # if !brand_id.nil? && !brand_type_id.nil? && brand_type_id != "" && brand_id != ""
#       
                # branch_type = BrandType.find(brand_type_id)
                # branch_name = Brand.find(brand_id)
# 
            # json = {"success" => 1, "message" => "success" ,"brand_type_name" => branch_type.type1, "brand_name" => branch_name.name}
    # else
            # json = {"success" => 0, "message" => "Required field's missing"}
    # end
    # render :json => json
  end
  
 
end

Posmtracker/app/helpers/posm_types_helper.rb
module PosmTypesHelper
end

Posmtracker/app/views/posm_types/_form.html.erb
<%= form_for(@posm_type) do |f| %>
  <% if @posm_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@posm_type.errors.count, "error") %> prohibited this posm_type from being saved:</h2>

      <ul>
      <% @posm_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Posmtracker/app/views/posm_types/edit.html.erb
<h1>Editing posm_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @posm_type %> |
<%= link_to 'Back', posm_types_path %>

Posmtracker/app/views/posm_types/index.html.erb
<h1>Listing posm_types</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posm_types.each do |posm_type| %>
  <tr>
    <td><%= link_to 'Show', posm_type %></td>
    <td><%= link_to 'Edit', edit_posm_type_path(posm_type) %></td>
    <td><%= link_to 'Destroy', posm_type, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Posm type', new_posm_type_path %>

Posmtracker/app/views/posm_types/new.html.erb
<h1>New posm_type</h1>

<%= render 'form' %>

<%= link_to 'Back', posm_types_path %>

Posmtracker/app/views/posm_types/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_posm_type_path(@posm_type) %> |
<%= link_to 'Back', posm_types_path %>