Posmtracker/config/routes.rb
Posmtracker::Application.routes.draw do
  

 

        root :to => "employees#index"

      get "/posm_tracker" => "employees#index"

  
  match ':controller(/:action(/:id))(.:format)'
  
  resources :company_details

  resources :branch_details

  resources :employee_roles

  resources :employees

  resources :uploaded_images
    
  resources :images_multi_brands
  
  resources :employee_authentications
  
  resources :brand_details
  
   resources :customer_details

  resources :posm_types
  
  resources :kd_details

  resources :principal_details

end

Posmtracker/app/models/kd_detail.rb
class KdDetail < ActiveRecord::Base
  # attr_accessible :title, :body
  set_table_name "KD_MASTER"
 
  alias_attribute :kd_code , :KD_code
  alias_attribute :kd_name , :KD_name
  
  attr_accessible :kd_code , :kd_name 

end

Posmtracker/app/controllers/kd_details_controller.rb
class KdDetailsController < ApplicationController
 
end

Posmtracker/app/helpers/kd_details_helper.rb
module KdDetailsHelper
end

Posmtracker/app/views/kd_details/_form.html.erb
<%= form_for(@kd_detail) do |f| %>
  <% if @kd_detail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kd_detail.errors.count, "error") %> prohibited this kd_detail from being saved:</h2>

      <ul>
      <% @kd_detail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Posmtracker/app/views/kd_details/edit.html.erb
<h1>Editing kd_detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @kd_detail %> |
<%= link_to 'Back', kd_details_path %>

Posmtracker/app/views/kd_details/index.html.erb
<h1>Listing kd_details</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @kd_details.each do |kd_detail| %>
  <tr>
    <td><%= link_to 'Show', kd_detail %></td>
    <td><%= link_to 'Edit', edit_kd_detail_path(kd_detail) %></td>
    <td><%= link_to 'Destroy', kd_detail, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Kd detail', new_kd_detail_path %>

Posmtracker/app/views/kd_details/new.html.erb
<h1>New kd_detail</h1>

<%= render 'form' %>

<%= link_to 'Back', kd_details_path %>

Posmtracker/app/views/kd_details/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_kd_detail_path(@kd_detail) %> |
<%= link_to 'Back', kd_details_path %>